### ISSUE TITLE
hot reload

### ISSUE THREAD

**Issue by ramboza** [patrikholcak/hot-loader-demo#3]
Hi ! 

cool and clean base project ! 
Thanks !

few notes:

1st - 
const NextApp = require('./app')**.default;**
(because app.js export default object, not a App.. and when you use require()  )

and hot reload not working when webpack detect changes on "counter page" 
"[HMR] Cannot check for update (Full reload needed),  [HMR] trySubscribe
addNestedSub... "
on Home it works !

**Comment by patrikholcak** [comment]
The HMR issue has been caused by `react-redux` v5. If you downgrade it back to stable (4.4.6), it will work just fine.

Will fix it along with the readme tomorrow.
Thanks! :)
