### ISSUE TITLE
es2015 and hot-loader

### ISSUE THREAD

**Issue by ramboza** [patrikholcak/hot-loader-demo#4]
Hello Patrik,

Thank you for your really nice and clean boilerplate!  👍 

I found 1 issue.. 

so, if you need to use ECMAScript  2015 features, then you need modify .babelrc, put "es2015" ... 
and then hot-reload will not work.. 

solution: 

_main.js_

`
module.hot.accept('./app', () => renderApp());
`

change on: 
```
module.hot.accept('./app', () => {
	const NextApp = require('./app').default;
	renderApp(NextApp);
})
```

may be with reducer needs to do the same... 

Thanks mate !

**Comment by ramboza** [comment]
sorry, this is already in your read.me :)

**Comment by patrikholcak** [comment]
No problem mate! The reducer might need to be re-required, haven’t tested that. Let me know and I can put it in the readme

**Comment by ramboza** [comment]
Cool ! 
yep, reducer must be reloaded in the same way as app ! 

store.replaceReducer(appReducer);

must be 

store.replaceReducer(require('./reducer').default);

Rox !!
